import React from "react";
import {Badge} from "antd";
import {EyeInvisibleOutlined, EyeOutlined} from "@ant-design/icons";

const operation_plan_area_data = [
    {
        name:"anterior_part_of_left_middle_frontal_gyrus",
        status:"未导入",
        color:"pink",
        visible:true
    },
    {
        name:"_left_globus_pallidus_pars_externa",
        status:"未导入",
        color:"red",
        visible:false
    },{
        name:"_left_globus_pallidus_pars_interna",
        status:"未导入",
        color:"yellow",
        visible:false
    },{
        name:"_left_subthalamic_nucleus",
        status:"未导入",
        color:"lightblue",
        visible:false
    },{
        name:"left_caudate_nucleus",
        status:"未导入",
        color:"orange",
        visible:false
    },{
        name:"left_putamen",
        status:"未导入",
        color:"cyan",
        visible:false
    },{
        name:"left_ventral_anterior_thalamic_nucleus",
        status:"未导入",
        color:"green",
        visible:false
    },{
        name:"left_ventral_lateral_thalamic_nucleus",
        status:"未导入",
        color:"blue",
        visible:false
    },
    {
        name:"left_lateral_dorsal_thalamic_nucleus",
        status:"未导入",
        color:"purple",
        visible:false
    },{
        name:"left_lateral_posterior_thalamic_nucleus",
        status:"未导入",
        color:"geekblue",
        visible:false
    },{
        name:"left_ventral_posterolateral_thalamic_nucleus",
        status:"未导入",
        color:"magenta",
        visible:false
    },{
        name:"anterior_part_of_right_middle_frontal_gyrus",
        status:"未导入",
        color:"volcano",
        visible:false
    },{
        name:"_right_globus_pallidus_pars_externa",
        status:"未导入",
        color:"gold",
        visible:false
    },{
        name:"_right_globus_pallidus_pars_interna",
        status:"未导入",
        color:"lime",
        visible:false
    },{
        name:"_right_subthalamic_nucleus",
        status:"未导入",
        color:"black",
        visible:false
    },{
        name:"right_caudate_nucleus,right_putamen",
        status:"未导入",
        color:"black",
        visible:false
    },

];

export default operation_plan_area_data;
